"""Narrow finance persistence capabilities. No adapter types cross this boundary."""

from __future__ import annotations

from contextlib import AbstractContextManager
from dataclasses import dataclass
from typing import Protocol

from core.effect import EffectSink
from core.event import Event
from core.identity import Id
from core.provenance import Provenance
from core.time import WallInstant
from core.trace import Trace
from personal_finance.application.model_codec import ModelRecord
from personal_finance.application.reconcile_codec import ReconcileRecord
from personal_finance.domain.accounts import Account
from personal_finance.domain.cash import (
    CashAllocation,
    CashBalanceObservation,
    CashCoverage,
    CashFloorChange,
    CashHold,
    CashRecords,
    CashRetirement,
    CashSchedule,
)
from personal_finance.domain.ledger import Draft, JournalEntry
from personal_finance.domain.models import ModelRecords
from personal_finance.domain.reconciliation import ReconcileRecords


class FinanceFailure(Exception):
    """Expected persistence/finance-policy rejection, safe to show locally."""


class StaleProjection(FinanceFailure):
    """Authoritative inputs changed before their derived cache could be committed."""


@dataclass(frozen=True, slots=True)
class LedgerInputs:
    accounts: tuple[Account, ...]
    entries: tuple[JournalEntry, ...]
    drafts: tuple[Draft, ...]
    revision: int
    cash: CashRecords = CashRecords()
    models: ModelRecords = ModelRecords()
    reconciliation: ReconcileRecords = ReconcileRecords()


@dataclass(frozen=True, slots=True)
class LocalApproval:
    id: Id
    draft_id: Id
    content_hash: str
    action: str
    principal: str
    profile: str
    policy_version: str
    approved_at: WallInstant
    expires_at: WallInstant


class FinanceUnitOfWork(EffectSink, Protocol):
    def accounts(self) -> tuple[Account, ...]: ...
    def entries(self, search: str = "") -> tuple[JournalEntry, ...]: ...
    def drafts(self) -> tuple[Draft, ...]: ...
    def revision(self) -> int: ...
    def draft(self, draft_id: Id) -> Draft: ...
    def entry(self, entry_id: Id) -> JournalEntry: ...
    def add_account(self, account: Account) -> None: ...
    def add_draft(self, draft: Draft) -> None: ...
    def check_open_date(self, effective_date: str) -> None: ...
    def check_open_range(self, start_date: str, end_date: str) -> None: ...
    def post_entry(self, entry: JournalEntry) -> JournalEntry: ...
    def consume_approval(self, approval: LocalApproval, entry_id: Id) -> None: ...
    def finish_draft(self, draft_id: Id, entry_id: Id) -> None: ...
    def replay(self, key: str, fingerprint: str) -> JournalEntry | None: ...
    def remember(self, key: str, fingerprint: str, entry_id: Id) -> None: ...
    def record_event(self, event: Event) -> None: ...
    def record_trace(self, trace: Trace, principal: str, input_hash: str) -> None: ...
    def save_projection(self, revision: int, payload: str, provenance: Provenance) -> None: ...
    def save_filter(self, name: str, query: str) -> None: ...
    def cash_records(self) -> CashRecords: ...
    def model_records(self) -> ModelRecords: ...
    def add_model_record(self, record: ModelRecord) -> None: ...
    def reconcile_records(self) -> ReconcileRecords: ...
    def add_reconcile_record(self, record: ReconcileRecord) -> None: ...
    def add_cash_schedule(self, schedule: CashSchedule) -> None: ...
    def add_cash_allocation(self, allocation: CashAllocation) -> None: ...
    def add_cash_hold(self, hold: CashHold) -> None: ...
    def add_cash_floor_change(self, change: CashFloorChange) -> None: ...
    def add_cash_observation(self, observation: CashBalanceObservation) -> None: ...
    def add_cash_coverage(self, coverage: CashCoverage) -> None: ...
    def add_cash_retirement(self, retirement: CashRetirement) -> None: ...
    def save_cash_projection(
        self, revision: int, horizon: int, payload: str, provenance: Provenance
    ) -> None: ...
    def save_model_projection(
        self, revision: int, payload: str, provenance: Provenance
    ) -> None: ...
    def save_reconcile_projection(
        self, revision: int, payload: str, provenance: Provenance
    ) -> None: ...


class FinanceRepository(Protocol):
    def transaction(self) -> AbstractContextManager[FinanceUnitOfWork]: ...
    def accounts(self) -> tuple[Account, ...]: ...
    def entries(self, search: str = "") -> tuple[JournalEntry, ...]: ...
    def drafts(self) -> tuple[Draft, ...]: ...
    def inputs(self) -> LedgerInputs: ...
    def cash_records(self) -> CashRecords: ...
    def model_records(self) -> ModelRecords: ...
    def reconcile_records(self) -> ReconcileRecords: ...
    def filters(self) -> tuple[tuple[str, str], ...]: ...
    def provenance(self, provenance_id: Id) -> Provenance | None: ...
